### Send POST request with json body
POST http://YWRtaW46YWRtaW4=@localhost:8035/create
Content-Type: application/json

{
  "full_link":"https://mail.ru/"
}

### Send POST request with json body
POST http://localhost:8040/create
Content-Type: application/json

{
  "full_link":"https://yandex.ru/"
}

###
GET http://localhost:8035/-/4AA88C41

###
#GET http://localhost:8035/stat/1f44b569210f42c0af57c9d88dc24b11

###
POST http://localhost:8035/stat
Content-Type: application/json

{
  "statistic_link":"625053f7f7b041b2bd4f04e587d29576"
}

### mail.ru
GET http://localhost:8080/




### Send POST request with json body
POST http://localhost:8001/create
Content-Type: application/json

{
  "full_link":"https://yandex.ru/"
}

### Send POST request with json body
POST http://localhost:8001/4B11BA43
Content-Type: application/json

{
  "short_link":"4B11BA43"
}


### Kubernetes
### Send POST request with json body
POST http://10.152.183.100:8042/create
Content-Type: application/json

{
  "full_link":"https://yandex.ru/"
}

