version: "3.9"

volumes:
  shortener-db-pg:

networks:
  localnet:

services:

  postgres:
    container_name: pg-shortener
    image: postgres:13.1
    ports:
      - 5432:5432
    volumes:
      #      - ./initDB:/docker-entrypoint-initdb.d
      #      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - shortener-db-pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1110
      POSTGRES_DB:  shotener-db
    restart: always
    networks:
      - localnet

  server:
    container_name: server
    image: docker.io/aivlev/shortener-srv:v2.0.1
    build: .
    ports:
      - 8042:8042
    environment:
      #     Переопределяем переменную окружения установленную в Docerfile.
      SRV_PORT: 8042
      SHORTENER_STORE: mem
      POSTGRES_DSN: "postgres://postgres:1110@postgres/shortener-db?sslmode=disable"
    depends_on:
      - postgres
    restart: always
    networks:
      - localnet

  client:
    container_name: client
    image: aivlev/shortener-cli:v2.0.1
    build: .
    ports:
      - 8080:8080
    environment:
      #     Переопределяем переменную окружения установленную в Docerfile.
      SRV_HOST: server
      SRV_PORT: 8042
      CLI_HOST: localhost
      CLI_PORT: 8080
    depends_on:
      - server
    restart: always
    networks:
      - localnet