openapi: 3.0.1
info:
  version: 1.0.0
  title: Shop
  description: Shortener сервис, позволяющий пользователю генерировать для произвольного URL’a его короткую версию.
  contact:
    name: send to email
    email: p.v.nedoshivin@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
    
tags:
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://mylocalhost.local
    
- name: link
  description: Operations about item
  externalDocs:
    description: Find out more about our store
    url: http://mylocalhost.local

paths:
  /user/login:
    post:
      tags:
      - user
      operationId: loginUser
      parameters:
      - name: username
        in: query
        description: The user name for login
        required: true
        schema:
          type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          headers:
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
        400:
          description: Invalid username/password supplied
          content: {}
          
  /user/logout:
    post:
      tags:
      - user
      summary: Logs out current logged in user session
      operationId: logoutUser
      responses:
        200:
          description: successful logout
          content: {}
  
  /link:
    get:
      tags:
      - link
      summary: Lists short links
      operationId: ListLinks
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Link'
      security:
        - api_key: []
          
    post:
      tags:
      - link
      summary: Add a new item to the store
      operationId: CreateItem
      requestBody:
        content:
          application/json:
            schema:
              properties:
                fullLink:
                  type: string
                  description: Creating a short link
      responses:
        200:
          description: successful create a short link
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Link'
        405:
          description: "Invalid input"
      security:
        - api_key: []
        
  /link/{shortLink}:  
    delete:
      tags:
      - link
      summary: Deletes a link
      operationId: DeleteLink
      parameters:
      - name: short_link
        in: path
        description: Short link to delete
        required: true
        schema:
          type: string
      responses:
        404:
          description: Short link not found
          content: {}
      security:
        - api_key: []    
      
  /stat/{shortLink}:
    get:
      tags:
      - link
      summary: Shows statistics of clicks on a short link
      operationId: GetShortLink
      parameters:
      - name: shortLink
        in: path
        description: short link conversion statistics to return
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Link'
        404:
          description: Short link not found
          content: {}
      security:
        - api_key: []
          
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        password:
          type: string
          
    Link:
      type: object
      properties:
        id:
          type: integer
          format: int64
        client_id:
          type: integer
          format: int64
        short_link:
          type: string
        full_link:
          type: string
        count:
          type: integer
          format: int64
        created_at:
          type: string


  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
