# API кубернетиса
apiVersion: v1
# kind показывает кубернетису, какой тип ресурса мы описываем
kind: Service
metadata:
  # name название пода который будет формироваться по spec описанной ниже
  name: k8s-shortener-srv-service
# описание типа сервиса
spec:
  # NodePort даёт каждой ноде внешний IP для обработки запросов со стороны
  type: ClusterIP # NodePort #ClusterIP
  # selector определяет для каких подов применим сервис
  selector:
    app: k8s-shortener-srv
  ports:
    - name: srv-http
      # принимает входящие запросы на этот порт и перенаправляет их на targetPort
      port: 8042
      # Порт внутри контейнера
      targetPort: 8042

